# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  NavBot_config = release
endif

PROJECTS := NavBot

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

NavBot:
ifneq (,$(NavBot_config))
	@echo "==== Building NavBot ($(NavBot_config)) ===="
	@${MAKE} --no-print-directory -C . -f NavBot.make config=$(NavBot_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f NavBot.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   NavBot"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"